[build]
  command = "npm run build-css && npm run build"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/feeds/search"
  to = "/.netlify/functions/search"
  status = 200

[[redirects]]
  from = "/api/feeds/interests"
  to = "/.netlify/functions/interests"
  status = 200

[[redirects]]
  from = "/api/feeds/user/:username"
  to = "/.netlify/functions/user?username=:username"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

